version: '3.7'

services:
  jenkins:
    container_name: jenkins
    user: root
    build: jenkins
    image: jenkins/docker
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
  
#   sonarqube:
#     container_name: sonarqube
#     image: sonarqube
#     ports:    
#       - 9000:9000
#     networks: 
#       - net
  
networks:
  net:
    driver: bridge